name=AIoT_Lib
version=1.0.0
author=ThangNguyen2106
maintainer=ThangNguyen2106 <0309231068@caothang.edu.vn>
sentence=High-performance AIoT framework for ESP32 with HiveMQ Cloud TLS and Generative AI readiness.
paragraph=Seamlessly connect ESP32 and ESP32-S3 to HiveMQ Cloud TLS, Generative AI (Gemini Flash), and modern responsive Captive Portal.
category=Communication
url=https://github.com/ThangNguyen2106-dash/AIoT_DEVERLOPMENT
architectures=esp32
includes=AIoT.h

