; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters = direct
board_build.partitions = min_spiffs.csv
build_flags = 
	-Os
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections

; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 115200
; board_build.partitions = min_spiffs.csv
; build_flags = 
; 	-Os
; 	-ffunction-sections
; 	-fdata-sections
; 	-Wl,--gc-sections



